<?php
include '../../../config.php';
include PATH_INCLUDE . 'TemplatePages.php';
include PATH_INCLUDE . 'ImagenPie.php';
include PATH_INCLUDE . 'ToolTip.php';
$urlPath = parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH);
$menuAsignaturaPath = getMenuAsignaturaPath($urlPath);
ob_start();
?>
<section>
  <h2>Estudios Subalternos, Ranahit Guha.</h2>

  <h3>ESTUDIOS SUBALERNOS</h3>
  <p>Esta corriente historiográfica surge de manera específica para explicar el desarrollo social de la India. Los estudios subalternos son un campo de estudio en la historia, así como de las ciencias sociales que se enfoca en la experiencia y las perspectivas de los grupos sojuzgados. Esta visión busca que los historiadores de los países postcoloniales, surgidos durante los procesos de liberación del siglo XX, buscarán romper con la herencia colonial respecto a cómo se pensaba y concebía la nación y la escritura de la historia, la cual es tanto reflexiva sobre la disciplina sus objetos de estudio, así como combativos, comprometidos con una visión de cambio social.</p>
  <p>En palabras del historiador especializado en historiografía china y estudios subalternos, Arif Dirlik:</p>
    <ul>
  <p>« […] los historiadores de Subaltern Studies [con] sus calificaciones de clase en la historia de la India, sus puntos de vista sobre la nación como categoría en disputa y su mandato de que la historia del capitalismo se entienda en términos de las consecuencias fracturadoras de la resistencia local y nacional […] estos enfoques representan la aplicación en la historiografía india de tendencias en la escritura histórica que estaban bastante extendidas en la década de 1970, bajo el impacto de historiadores sociales como E. P. Thompson, Eric Hobsbawm y toda una serie de autores. Todo esto indica que los historiadores de la India fueron participantes en las transformaciones del pensamiento histórico en todas las áreas, transformaciones en las que las sensibilidades del Tercer Mundo fueron solo uno entre una serie de eventos que también incluyeron el 
  <?php renderTooltip ('posestructuralismo', 'Está asociado con los trabajos de una serie de filósofos y teóricos sociales europeos y norteamericanos que a mediados de la década de 1960 desarrollan sus ideas como una crítica al estructuralismo, al cual presentan varios cuestionamientos. El posestructuralismo se ha ligado a autores como Michel Foucalt o Jacques Derrida','bottom');?>, nuevas formas de pensar sobre el marxismo, y la entrada en la historia del feminismo. Sin duda, creo que es muy importante que las sensibilidades del Tercer Mundo entren en juego repetidamente para contrarrestar la tendencia hacia el imperialismo cultural de los pensadores e historiadores del Primer Mundo que aplican conceptos de derivación del Primer Mundo globalmente sin pensar dos veces en las diferencias sociales.» p.340. (Dirlik, Arif. The Postcolonial Aura: Third World Criticism in the Age of Global Capitalism, en Critical Inquiry, Vol. 20, No. 2 (invierno, 1994), pp. 328-356)</p>
    </ul>
  <p>El término <b>subalterno</b> se refiere a aquellos grupos sociales que han sido marginados, oprimidos y excluidos del poder político y económico, y que no han tenido una voz en la historia oficial, que, por su complejidad, no pueden estudiarse de manera única con sólo una categoría de análisis, como sería el concepto de clase social, pues a su interior, estos grupos son diversos, enfrentados entre sí y con una serie de contradicciones y desarrollos ideológicos y de autopercepción desiguales, por lo cual, su estudio requiere, necesariamente de poder contrastarlos, desde abajo, con la visión aceptada por la historia académica formal. Procesos como la Guerra Cristera en nuestro país, son una muestra de esta complejidad de estudio por sus componentes sociales, ideológicos y los estratos campesinos del Bajío y su contraste con los grupos urbanos del norte y centro de México.</p>
  <p>Los estudios subalternos surgen como una crítica a la historia convencional, que se enfoca en la élite y en los eventos políticos y económicos más importantes. En cambio, los estudios subalternos buscan analizar y comprender la experiencia y la perspectiva de los grupos subalternos, incluyendo a los trabajadores, los campesinos, las mujeres, los pueblos indígenas y otras minorías.</p>
  <p>El iniciador de esta corriente es el historiador de origen indio, radicado en Londres, Ranajit Guha, fundador de la Escuela de Estudios Subalternos en la década de los ochenta, en Londres. Tiene numerosos artículos publicados en la revista Estudios Subalternos; dentro de sus libros tenemos Elementary Aspects of Peasant Insurgency in Colonial India, Dominance whitout Hegemony  y es editor de los Subaltern Studys. Writings of South Asia History and Society. En español tenemos obras como La historia dentro de la Historia Universal y Las voces de la historia y otros estudios subalternos.</p>
  <p>La Escuela de Estudios Subalternos buscan recuperar la voz, en las palabras del autor mencionado, revelar el punto de vista de los subalternos, de aquellos que por razones del poder estatal o las posturas ideológicas, formadas en contexto europeo, ya sea las visiones del nacionalismo hindú o las visiones de los partidos políticos marxistas, que fueron, son, dominantes dentro de la historiografía de la India. De igual manera la experiencia de los grupos marginados de la sociedad o aquellas culturas dominadas a las cuales se les impone una visión y escritura de la historia; buscan analizar cómo han contribuido a la formación de la sociedad, así como la cultura en su conjunto. Esto implica estudiar sus culturas, además de las prácticas populares, su resistencia, e impulsar la lucha contra la opresión y la exclusión, fomentando la contribución a la creación de nuevas formas de pensamiento y acción:</p>
    <ul>
    <p>«Hay expresiones en muchos idiomas, no sólo en los de la India, que hablan de acontecimientos y hechos históricos. Estas expresiones se consideran de sentido común y se da por supuesto que los miembros de las respectivas comunidades lingüísticas las comprenden. Sin embargo, la corteza del sentido común comienza a resquebrajarse en cuanto se pregunta qué significa el adjetivo «histórico» en estas expresiones. Su función es, evidentemente, la de consignar determinados acontecimientos y hechos a la historia. Pero, en primer lugar, ¿quién los elige para integrarlos en la historia? Porque está claro que se hace una cierta discriminación —un cierto uso de valores no especificados y de criterios implícitos— para decidir por qué un acontecimiento o un acto determinados deben considerarse históricos y no otros. ¿Quién lo decide, y de acuerdo con qué valores y criterios? Si se insiste lo suficiente en estas preguntas resulta obvio que en la mayoría de los casos la autoridad que hace la designación no es otra que una ideología para la cual la vida del estado es central para la historia. Es esta ideología, a la que llamaré «estatismo», la que autoriza que los valores dominantes del estado determinen el criterio de lo que es histórico». Guha, las voces de la historia, p.17.</p>
  </ul>
  <p>Con relación al método de la investigación histórica, Guha parte de una pregunta ¿quién y cómo se eligen los temas para la investigación de la historia? Su respuesta es el estatismo:</p>
    <ul>
  <p>«Por esta razón puede decirse que, en general, el sentido común de la historia se guía por una especie de  
    <?php renderTooltip ('estatismo', 'Guha utiliza este término en los Estudios Subalternos para definir una ideología «para la cual la vida del Estado es central para la historia», cuya función es escoger por nosotros, y para nosotros, determinados acontecimientos como "históricos", como dignos de ocupar un lugar central en el trabajo de investigación de los historiadores, que en la mayoría de los casos implica aceptación y defensa del orden establecido y que orienta el curso entero de la historia del origen del  político y social, los valores y la cultura del entorno del propio historiador.','bottom');?>  que le define y evalúa el pasado. Ésta es una tradición que arranca de los orígenes del pensamiento histórico moderno en el Renacimiento italiano. Para los grupos dirigentes de las ciudades-estado del siglo XV, el estudio de la historia servía para la educación en materia de política y gobierno, indispensables para desempeñar su papel como ciudadanos y como monarcas. Es lógico, por ello, que, para Maquiavelo, el intelectual más representativo de aquellos grupos, «el estudio de la historia y el estudio del arte de gobernar debieran ser esencialmente lo mismo». Ibíd., p. 15 tomado de la introducción de Josep Fontana</p>
    </ul>
  <p>La Historia, vista desde esta perspectiva implica una forma de normalización de sus temas, personajes y estructuras narrativas, con las cuales, desde el poder, en el caso de este autor, desde la metrópoli que dominó a la India, quien desarrolla la visión de su historia en el siglo XIX; para esto utiliza los libros, tanto de investigación como de texto para formar una idea para un grupo de lectores, las élites, quienes reproducen este discurso y lo presentan como propio a las clases subalternas. El autor nos dice:</p>
   <ul>
  <p>«fue esta literatura, desde los manuales escolares hasta las novelas históricas, la que ayudó a institucionalizar la investigación histórica al constituirla en una serie de géneros literarios imaginativos y discursivos equipados con sus propios cánones y narratologías. En conjunto, la institucionalización del estudio de la historia tuvo el efecto de asegurar una base estable al estatismo dentro de las disciplinas académicas y de promover hegemonía» Ibíd. p. 18.</p>
  </ul>
  <p>Comprender la historia desde esta óptica nos permite entonces hacer una historia que contrarreste esta visión y sea, como se dio en la visión marxista, en un instrumento de liberación y de orientación para una política revolucionaria. Esta característica de los Estudios Subalternos tiene impacto en América Latina y propone una historia desde abajo, que rompa con la visión hegemónica que impone una metrópoli, tal como lo demuestra el grupo Latin American Subaltern Studies, creado a principios de los años noventa e integrado por historiadores y académicos latinoamericanos y estadounidenses.</p>
   <div class="mx-auto max-w-md">
 <?php
  renderImage('th2-u3-ranajitguha.webp','Ranajit Guha', '','Wikimedia Commons.');
  ?>
 </div>


</section>
<?php
$content = ob_get_clean();
renderTemplatePage($menuAsignaturaPath, $content);
?>
