<?php
include '../../../config.php';
include PATH_INCLUDE . 'TemplatePages.php';
$urlPath = parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH);
$menuAsignaturaPath = getMenuAsignaturaPath($urlPath);
ob_start();
?>
<p>Lorem ipsum dolor sit amet, <a href="#" target="_blank">consectetur adipiscing elit</a>. Phasellus eget condimentum neque. In elementum nec leo quis sagittis. Cras sit amet mi ornare, placerat urna id, aliquam felis. Sed vel quam neque. Aliquam auctor leo sem, in semper lorem cursus eget. Vestibulum at quam tellus. Lorem ipsum dolor sit amet, <a href="#" target="_blank">consectetur adipiscing elit</a>. Nunc a gravida tortor. Quisque laoreet euismod nunc in venenatis. Ut vel eros est. Nam consectetur tortor quis vulputate pellentesque.</p>
<p>Vestibulum molestie ultricies elit, quis aliquam risus elementum in. Maecenas non sollicitudin metus. Praesent tempus erat ut mi sollicitudin bibendum. Ut magna nunc, blandit vel tempor ac, euismod ut ligula. Donec at iaculis augue, vel blandit dolor. Vivamus lacinia vitae dui eget venenatis. Sed non vehicula enim. Aliquam mattis est eget placerat bibendum. Nulla nec lectus turpis. In convallis malesuada magna, vitae condimentum libero dapibus ac. Donec vel mauris vel sem molestie placerat quis a enim.</p>
<p>Vestibulum venenatis, erat in congue vestibulum, sapien lacus facilisis dolor, vel finibus nisl magna eget urna. Aenean aliquam ullamcorper odio dapibus feugiat. Vestibulum at arcu pulvinar, efficitur sapien eu, tincidunt tortor. Etiam dapibus urna id mollis placerat. Integer a libero ac mauris vestibulum mollis vitae et enim. Etiam nec diam at erat bibendum pretium. Proin dictum, dui vitae blandit placerat, leo augue sagittis risus, ac maximus nibh neque ac lorem. Ut fringilla lobortis velit, at convallis purus dapibus quis. Donec quis turpis tincidunt, finibus sem in, convallis lorem. Aenean ornare mollis aliquam. Morbi ultrices tortor nec orci auctor dapibus. Nunc gravida dui lectus, sit amet facilisis sem feugiat sit amet. Nullam quis pellentesque nisl. Aenean porttitor nulla nisi. Sed a diam quis mauris sodales dapibus. Aenean commodo porta leo eget iaculis.</p>
<p>Praesent vitae ipsum a tortor facilisis aliquam. Aenean ac ipsum ullamcorper, venenatis nisi rhoncus, aliquam neque. Integer vel ipsum id lectus sodales tincidunt. Maecenas finibus vestibulum augue vel fermentum. Nulla consectetur consequat mattis. Donec eget ullamcorper augue. Curabitur rhoncus ligula arcu, at efficitur lacus pharetra nec.</p>
<p>Etiam finibus in felis non pharetra. Integer sagittis sagittis elit, et interdum lorem pretium eget. Pellentesque elit ex, pharetra eu dapibus vitae, aliquet in eros. Praesent placerat urna vitae odio scelerisque, et tempus lorem placerat. Nunc euismod justo elit, id vulputate nibh tempor vitae. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam cursus dolor mauris. Proin egestas at quam tincidunt ornare. Donec ac bibendum ipsum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nam ultricies et nunc in aliquam. Maecenas iaculis rhoncus gravida. Lorem ipsum dolor sit amet, <a href="#" target="_blank">consectetur adipiscing elit</a>. Donec convallis urna vel ipsum aliquet porta.</p>
<p>Integer vulputate tortor justo, quis sollicitudin dui tempor ut. Aliquam nec commodo risus, in luctus ipsum. Curabitur eget lectus eu nisi tincidunt varius posuere nec enim. Nullam venenatis dignissim erat vitae molestie. Quisque vulputate magna eu facilisis volutpat. Ut malesuada turpis non eros accumsan, vitae pulvinar orci commodo. Quisque commodo facilisis lorem, vitae vulputate odio dignissim id. Vivamus dapibus pharetra eros, sit amet ultricies dui placerat ac. Nullam sodales ante neque, nec maximus velit euismod non.</p>
<?php
$content = ob_get_clean();
renderTemplatePage($menuAsignaturaPath, $content);
?>
