<?php
include '../../../config.php';
include PATH_INCLUDE . 'TemplatePages.php';
include PATH_INCLUDE . 'ActividadIframe.php';
include PATH_INCLUDE . 'ImagenPie.php';
include PATH_INCLUDE . 'ToolTip.php';
$urlPath = parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH);
$menuAsignaturaPath = getMenuAsignaturaPath($urlPath);
ob_start();
?>
<section>
  <h2>HAYDEN WHITE</h2>
  <p>Se trata de un filósofo, historiador y escritor norteamericano, autor, entre otras obras, de Metahistoria. La imaginación histórica en la Europa del siglo XIX.  En su trabajo reflexiona sobre la historia, por lo que, a fin de cuestionar a los historiadores modernos, regresa al estudio de los filósofos del siglo XIX y a las visiones que sobre la historia se tienen en ese siglo con el fin de recuperar las bases de una historia posmoderna.</p>
  <p>Desde la perspectiva de Hayden White el historiador busca presentar ciertas perspectivas del mundo, sin mostrar una descripción o análisis exhaustivos de todos los fenómenos, sino está interesado sólo en ciertos aspectos, ya que al escribir historia no se busca mostrar lo mismo que otros ya hicieron, sino presentar de manera personal, desde su perspectiva los hechos. (White. El peso de la historia, p. 31)</p>
  <ul>
  <p>«Pero la historia es, según mi forma de ver, una construcción, más específicamente un producto del discurso […]. Sin duda, en nuestros tiempos, los historiadores desean ser objetivos, y contar la verdad, así como agudos en lo que tienen que decir del pasado, lo que, en la práctica, normalmente significa ocultar sus propias actividades como compositores de esa condición de existencia llamada “historia” […] Creo que la aproximación más  provechosa al estudio del escrito histórico toma su aspecto literario más seriamente de lo que permite la vaga noción de “estilo” […] Como un discurso acerca de las cosas ya no perceptibles, la historiografía debe construir, entendiendo por ello imaginar y conceptualizar, sus objetos de interés antes de poder proceder a aplicarles los tipos de procedimientos que desea usar para explicarlos o comprenderlos. Existen muy buenas razones por las que la historia nunca ha sido convertida en una ciencia -sin perder su identidad como historia-. Esto se debe a que las figuras y los giros discursivos (tropos), más imaginarios que conceptuales, son necesarios para la construcción de objetos de interés de la historia como posibles temas de una representación específicamente historiológica. Este elemento imaginativo no puede ser cercenado del escrito histórico sin privar al pasado de su encanto y su pathos, es decir su “pasividad”.» White, El texto histórico como artefacto literario, p 43-45.</p>
  <p>Los acontecimientos en su inicio son neutrales, es el historiador quien decide configurarlos de acuerdo con la estructura de la trama que busca presentar. Así el historiador organiza los acontecimientos de acuerdo con esta trama para presentar un relato comprensible. (White. El texto histórico…, p. 113)</p>
  <p>Al escribir historia el historiador presenta una visión, por lo que es importante considerar que es una perspectiva entre otras muchas, por lo que debe asumir que «no existe una perspectiva correcta para cualquier objeto de estudio, sino muchas perspectivas, cada una de las cuales necesita su propio estilo de representación».” (White. El peso de la historia, p. 32)</p>
  </ul>
  <p>Desde el punto de vista de White el trabajo del historiador es importante en tanto que pueda apoyar en la resolución de los problemas de su época. De manera que el conocimiento del pasado es importante en tanto que permite transitar responsablemente hacia el futuro. El estudio del pasado tiene la función de educar a los hombres en el conocimiento del presente que prepare y acepte “la responsabilidad del individuo en el diseño del futuro” (White. El peso de la historia, p. 33)</p>
  <h4>La historia</h4>
  <p>Hayden White considera que el historiador no puede reflexionar sobre su trabajo, ya que no puede ser objetivo al ser quien construye la investigación histórica, por lo que le toca a la 
    <?php renderTooltip ('Metahistoria', 'Este término se utiliza como sinónimo de filosofía de la historia, como es el caso del historiador británico Arnold J. toynbee. Algunas veces el término se usa como sinónimo de la filosofía de la historia., pero no da una definición precisa, sino que afirma que está por definirse. Nuestro autor lo plantea como todo el contexto, entorno, en el cual los historiadores hacen su investigación. El entorno puede hacer que se distorsione la visión de su objeto de estudio, es decir, distorsionan, por su entorno, la respuesta que se da a la investigación del pasado.','bottom');?> hacer la reflexión que el historiador no puede hacer sobre el quehacer histórico. De manera que, cuando se hace una investigación se debe estar preparado para hacer preguntas que permitan alcanzar aquello que está por encima de los presupuestos que sostienen a la investigación de manera que se puedan resolver problemas que se tratan de resolver. </p>
  <p>De esta forma, la metahistoria retoma las reflexiones de los filósofos del siglo XIX en torno a cuestionar el trabajo del historiador, haciéndose preguntas como “¿Cuál es el estatus epistemológico de las explicaciones históricas, comparadas con otros tipos de explicaciones que podrían ofrecerse para dar cuenta de los materiales con que los historiadores tratan generalmente?” Así los filósofos vuelven al cuestionamiento y reflexión de la historia y su relación con otras disciplinas; además de cuestionar la relación de la historia pasada con el presente. (White. El peso de la historia, p. 108-109) </p>
  <p>El fin de la historia es inculcar en los hombres la conciencia de su presente como parte de elecciones humanas que pueden cambiar o ser alteradas por otros actos humanos. Lo que implica que la historia muestra el cambio liberando el presente del pasado. La historia debe ser un elemento que eduque para enfrentar el cambio en la vida contemporánea. “Porque la discontinuidad, el rompimiento y el caos son el terreno de nuestro tiempo.” (White. El peso de la historia, p. 33)</p>
  <p>En este sentido el conocimiento de los hechos históricos es dado en función de las preguntas que el historiador se hace para dar una narración de los acontecimientos. En la recuperación de los hechos, a través de los registros documentales, lo primero que el historiador hace es un “ejercicio de imaginación especulativa” debido a que en la recuperación la información aparece fragmentada, donde los hechos aparecen de manera aislada. (White. El peso de la historia, p. 30-32) </p>
  <p>Haciendo las preguntas correctas el historiador toma la información que recupera y elabora un escrito discursivo en el que se narran relatos construidos a partir de crónicas, con estas se reúnen los hechos que se van relacionando en una trama, esto es en una narración o relato. (White. El peso de la historia, p. 111-112) </p>
  <h3>La objetividad histórica.</h3>
  <p>Hayden White considera que es difícil hacer una historia objetiva, ya que el historiador al realizar su objeto de estudio es probable que tenga una postura de manera que es parcial. </p>
  <p>La historia es un escrito discursivo, en el que el historiador narra un relato mediante la unión de hechos, trabaja a partir de la evidencia que le lleva a formular preguntas que pueden ser realizadas con el fin de resolver problemas, de manera que la historia no tiene compromisos, pero el historiador tiene una postura desde el momento en que elige el tema que le interesa, al involucrarse también muestra su visión en cuanto a la explicación que brindan del acontecimiento.</p>
  <p>Los historiadores explican los acontecimientos partiendo de las evidencias históricas que encuentran al descubrir el relato o relatos contenidos en ellos, de manera que se incorporan en un relato «suprimiendo o subordinado algunos de ellos y énfasis en otros, la caracterización, la repetición de motivos, la variación de tono y el punto de vista, la estrategias descriptivas alternativas y similares; en suma, mediante todas las técnicas que normalmente esperaríamos encontrar en el tramado de una novela o una obra».. (White. El texto histórico, p. 113). De manera que es el historiador quién asigna el sentido y estructura de la trama del acontecimiento.</p>
  <p>El historiador busca información de acuerdo con el tipo de narración que quiere relatar, en este sentido la historia es un escrito discursivo, en el que se presentan coherentemente las explicaciones de los acontecimientos, esto es en una narrativa histórica, lo que hace común a la historia con la literatura. ((White. El texto histórico…, p. 109-111)</p>
  <p>Considera que no hay una perspectiva correcta para el objeto de estudio, sino que hay muchas perspectivas, las que requieren de una forma de representarlas, la elección del orden de los datos permite al historiador elegir el orden de un discurso que implica una lógica. Respetando la lógica del discurso que el historiador establece para unir los datos del acontecimiento narrado, es que se pueden emplear los conocimientos científicos aportados por otras ciencias como la psicología, la cibernética. (White. El peso de la historia, p. 32)</p>
  <p>Al estructurar su discurso el historiador presenta una posible explicación de los acontecimientos, misma que comparte con un lector que de principio ve en la historia datos extraños por la distancia que los separa con el presente y que son parte de una forma de vida diferente. Así al conocer la narración del historiador sobre los acontecimientos el lector se da cuenta de que el relato presenta una explicación, por lo que al leer el relato el lector percibe que ha comprendido, por lo que los acontecimientos pasan de ser extraños o ajenos a ser familiares y comprensibles. Elemento que se explica a través de la estructura de la trama del relato. (White. El texto histórico…, p. 116-117)</p>
  <p>Haciendo una crítica a la escuela de los Annales marca que no es importante el uso de nuevas metodologías para allegarse al conocimiento histórico, por lo que es preciso el uso de técnicas artísticas modernas, en las que se busque ver a la historia como una narración adecuada a los hechos.</p>
  <h4>Metodología</h4>
  <p>Hayden White nos explica que el historiador es un narrador de los acontecimientos, por lo que parte de su capacidad para elaborar un relato histórico, plausible con sentido a partir de la unión de hechos. Da sentido a la información que se presenta de manera fragmentada e incompleta, apoyándose en la imaginación constructiva con el que establece cuál es el caso a partir de la evidencia disponible y las propiedades formales que le muestra el formular las respuestas correctas.</p>
  <p>Con la evidencia encuentra el relato escondido bajo el relato aparente, así el historiador explica la evidencia histórica cuando descubre el relato o relatos contenidos en ellos. De manera que el relato no es un conjunto de acontecimientos históricos registrados casualmente, los acontecimientos son incorporados en un relato mediante la supresión, subordinación, énfasis que el historiador les brinda. (White. El texto histórico…, p. 112-113)</p>
  <div class="mx-auto max-w-md">
  <?php
  renderImage('th2-u3-hydenwhite.webp','Hyden White', 'https://upload.wikimedia.org/wikipedia/commons/3/32/%E0%B2%B9%E0%B3%87%E0%B2%A1%E0%B2%A8%E0%B3%8D_%E0%B2%B5%E0%B3%88%E0%B2%9F%E0%B3%8D.jpg ','Wikimedia Commons.');
  ?>
  </div>
  <h4>EL SIGLO DE LA HISTORIA.</h4>
  <p>El siglo XX nos presenta, como hemos visto en la unidad precedente, consolidó nuevos temas, el uso de nuevas fuentes y nuevos problemas para la investigación histórica, y también distintas corrientes historiográficas. La historia, vista como un discurso político,  se convierte, gracias a los medios de difusión masiva en un elemento ideológico que busca ofrecer una sola visión del mundo, tal como pasó, por ejemplo con la caída del llamado socialismo real y la aparición del capitalismo salvaje. En este sentido, los autores de la posmodernidad buscan analizar, así como encontrar el sentido no sólo de un proceso histórico, sino en cómo se comunica el mismo, es decir, analizan también las formas en las que se escribe la historia como un elemento central de su trabajo: la objetividad de la historia se cuestiona, pero no se rechaza. La posmodernidad enfatiza la característica de comunicación de la historia y, al relativizar sus planteamientos, exige del lector un ejercicio no de aceptación incondicional, sino de crítica constante de las verdades, que no son absolutas en nuestra disciplina.</p>
  <p>A continuación vamos a repasar nuestra lección, para ello te pedimos que realices esta actividad de repaso, la cual te permitirá identificar tu aprovechamiento en la presente lección.</p>
  <?php ob_start(); ?>
    <p></p>
  <?php
    $ActividadContent = ob_get_clean();
    renderActividad('u3t3a2', "Actividad de repaso", $ActividadContent);
  ?>
  <?php ob_start(); ?>
    <p>Para continuar, realiza la Actividad entregable: El método del historiador en la posmodernidad.</p>
  <?php
    $ActividadContent = ob_get_clean();
    renderActividad('u3t3a3', "El método del historiador en la posmodernidad.", $ActividadContent);
  ?>
  <p>Has llegado al final del curso. Esperamos que, en este curso aprecies ahorra a la historia de manera distinta, no sólo como la acumulación de información de hechos históricos, sino que para llegar a mostrarlos, existe detrás una idea de lo que es la historia, de cómo en casi doscientos años afinamos cada vez más como sociedad, las formas de explorar y acercarnos al pasado, no como algo muerto, sino como formación del presente. Ahora comprendes que la historia siempre se estudia desde el momento actual y los problemas que investigamos, en las sociedades que nos antecedieron, sirven para explicar nuestro desarrollo como sociedad y nuestro papel como individuos dentro de la misma.</p>
  <p>Conocer que existen distintas escuelas historiográficas te permite comprender que , como ciencia, la historia no es una y acabada, sino que es un proceso en el cual las sociedades y sus miembros, se comprenden siempre en construcción a futuro, pero con raíces en el conocimiento de su pasado.</p>
  <p>¡No olvides lo aprendido y sigue investigando!</p>


</section>
<?php
$content = ob_get_clean();
renderTemplatePage($menuAsignaturaPath, $content);
?>