name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build project
      run: npm run build
      
    - name: Create deployment package
      run: |
        # Crear un archivo tar.gz con solo los archivos necesarios
        tar -czf pel-25-$(date +%Y%m%d-%H%M%S).tar.gz \
          --exclude='*.map' \
          --exclude='node_modules' \
          --exclude='.git' \
          --exclude='.github' \
          --exclude='src' \
          --exclude='*.md' \
          --exclude='package*.json' \
          --exclude='webpack.config.js' \
          --exclude='tailwind.config.mjs' \
          --exclude='postcss.config.mjs' \
          dist/
          
    # Opci칩n 1: Despliegue por SFTP/FTP
    - name: Deploy via SFTP
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      if: false # Cambiar a true cuando configures las variables FTP
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: 22
        local_path: './dist/*'
        remote_path: '/path/to/your/web/directory/'
        delete_remote_files: true
        
    # Opci칩n 2: Despliegue por rsync (RECOMENDADO)
    - name: Deploy via rsync
      if: false # Cambiar a true cuando configures las variables SSH
      run: |
        # Instalar rsync si no est치 disponible
        sudo apt-get update && sudo apt-get install -y rsync
        
        # Sincronizar solo archivos modificados
        rsync -avz --delete \
          --exclude='*.map' \
          --progress \
          ./dist/ \
          ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:${{ secrets.DEPLOY_PATH }}
          
    # Opci칩n 3: Subir artefacto para despliegue manual
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: production-build
        path: |
          dist/
          !dist/**/*.map
        retention-days: 30
